from __future__ import annotations

import json
from pathlib import Path

from .scanner import ProjectSummary


def write_outputs(root: Path, summary: ProjectSummary, force: bool = False) -> list[Path]:
    agent_dir = root / ".agent"
    outputs = {
        root / "AGENTS.md": agents_md(summary),
        root / "CLAUDE.md": claude_md(summary),
        root / "CODEX.md": codex_md(summary),
        agent_dir / "context.json": json.dumps(summary.to_dict(), indent=2) + "\n",
        agent_dir / "checklist.md": checklist_md(summary),
    }
    written: list[Path] = []
    agent_dir.mkdir(exist_ok=True)
    for path, content in outputs.items():
        if path.exists() and not force:
            continue
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def agents_md(s: ProjectSummary) -> str:
    return f"""# Agent Guide for {s.name}

This file was generated by `agent-ready` to help AI coding agents work safely and effectively in this repository.

## Project Snapshot

- Name: `{s.name}`
- Languages: {fmt(s.languages)}
- Frameworks: {fmt(s.frameworks)}
- Package managers: {fmt(s.package_managers)}

## Important Files

{bullets(s.important_files) or '- None detected'}

## Common Commands

### Test
{code_list(s.test_commands)}

### Build
{code_list(s.build_commands)}

### Lint
{code_list(s.lint_commands)}

## Risk Areas

{bullets(s.risk_areas) or '- None detected'}

## Agent Working Rules

- Read this file, the README, and relevant tests before editing.
- Prefer small focused diffs.
- Run the relevant commands listed above before proposing a PR.
- Do not print or commit secrets, local env values, tokens, private keys, or production credentials.
- Be careful around files related to deployment, auth, payments, database migrations, and generated output.
- If a command cannot run locally, explain why and provide the closest verification performed.

## Suggested First Steps

1. Inspect the relevant files for the issue.
2. Identify the smallest safe change.
3. Add or update tests if practical.
4. Run the commands above.
5. Summarize behavior changes and remaining risk.
"""


def claude_md(s: ProjectSummary) -> str:
    return f"""# Claude Code Instructions

Repository: `{s.name}`

Use this as the first context file when working in Claude Code.

## What To Know

- Main languages: {fmt(s.languages)}
- Frameworks: {fmt(s.frameworks)}
- Key directories: {fmt(s.top_directories)}
- Risk areas: {fmt(s.risk_areas)}

## Verification Commands

Test:
{code_list(s.test_commands)}

Build:
{code_list(s.build_commands)}

Lint:
{code_list(s.lint_commands)}

## Claude-Specific Rules

- Do not run destructive shell commands without explicit user approval.
- Before editing, locate the relevant tests or examples.
- Keep changes minimal and explain verification clearly.
- Avoid broad refactors unless the task explicitly asks for them.
"""


def codex_md(s: ProjectSummary) -> str:
    return f"""# Codex Instructions

Repository: `{s.name}`

## Operating Mode

- Work as a careful coding agent.
- Preserve user changes.
- Prefer targeted edits over rewrites.
- Run practical verification before final response.

## Detected Stack

- Languages: {fmt(s.languages)}
- Frameworks: {fmt(s.frameworks)}
- Package managers: {fmt(s.package_managers)}

## Commands

Test:
{code_list(s.test_commands)}

Build:
{code_list(s.build_commands)}

Lint:
{code_list(s.lint_commands)}

## Files To Inspect First

{bullets(s.important_files[:20]) or '- README and tests'}
"""


def checklist_md(s: ProjectSummary) -> str:
    return f"""# Agent Readiness Checklist

## Repo Understanding

- [ ] README inspected
- [ ] Stack identified: {fmt(s.languages)}
- [ ] Important files reviewed
- [ ] Risk areas reviewed: {fmt(s.risk_areas)}

## Before Editing

- [ ] Issue or task acceptance criteria understood
- [ ] Relevant tests located
- [ ] Minimal change plan written

## Before PR / Final Answer

- [ ] Tests/build/lint run where practical
- [ ] Behavior change summarized
- [ ] Risk and untested paths disclosed
- [ ] No secrets or generated junk included
"""


def fmt(values: list[str]) -> str:
    return ", ".join(f"`{v}`" for v in values) if values else "not detected"


def bullets(values: list[str]) -> str:
    return "\n".join(f"- `{v}`" for v in values)


def code_list(values: list[str]) -> str:
    if not values:
        return "```text\nnot detected\n```"
    return "\n".join(f"```bash\n{value}\n```" for value in values)
