from __future__ import annotations

import json
import os
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

IGNORED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "target",
    "__pycache__",
    ".next",
    ".turbo",
}

IMPORTANT_FILES = [
    "README.md",
    "CONTRIBUTING.md",
    "AGENTS.md",
    "CLAUDE.md",
    "CODEX.md",
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "go.mod",
    "Cargo.toml",
    "Makefile",
    "Dockerfile",
]

RISK_PATTERNS = {
    "env files": [".env", ".env.local", ".env.production"],
    "database migrations": ["migrations", "prisma", "schema.sql"],
    "deployment": [".github/workflows", "Dockerfile", "docker-compose.yml", "deploy"],
    "payments or wallet": ["stripe", "wallet", "payment", "checkout", "web3"],
    "security-sensitive": ["auth", "jwt", "token", "secret", "crypto"],
}


@dataclass
class ProjectSummary:
    root: str
    name: str
    languages: list[str]
    frameworks: list[str]
    package_managers: list[str]
    important_files: list[str]
    test_commands: list[str]
    build_commands: list[str]
    lint_commands: list[str]
    ci_workflows: list[str]
    risk_areas: list[str]
    top_directories: list[str]
    generated_at: str

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def scan(root: Path) -> ProjectSummary:
    root = root.resolve()
    files = list(iter_files(root))
    names = {p.name for p in files}
    rels = {rel(root, p) for p in files}
    languages = detect_languages(files)
    package_managers = detect_package_managers(names)
    frameworks = detect_frameworks(root, files)
    important = sorted(path for path in rels if Path(path).name in IMPORTANT_FILES or path.startswith(".github/workflows/"))
    tests, builds, lints = detect_commands(root, names)
    workflows = sorted(path for path in rels if path.startswith(".github/workflows/"))
    risks = detect_risks(root, files, rels)
    dirs = top_directories(root, files)
    return ProjectSummary(
        root=str(root),
        name=root.name,
        languages=languages,
        frameworks=frameworks,
        package_managers=package_managers,
        important_files=important[:50],
        test_commands=tests,
        build_commands=builds,
        lint_commands=lints,
        ci_workflows=workflows[:30],
        risk_areas=risks,
        top_directories=dirs,
        generated_at="generated by agent-ready",
    )


def iter_files(root: Path) -> Iterable[Path]:
    for current, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if (d not in IGNORED_DIRS and not d.startswith(".")) or d == ".github"]
        for file in files:
            path = Path(current) / file
            if path.is_file() and path.stat().st_size <= 500_000:
                yield path


def rel(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def detect_languages(files: list[Path]) -> list[str]:
    ext_map = {
        ".py": "Python",
        ".ts": "TypeScript",
        ".tsx": "TypeScript/React",
        ".js": "JavaScript",
        ".jsx": "JavaScript/React",
        ".go": "Go",
        ".rs": "Rust",
        ".sol": "Solidity",
        ".java": "Java",
        ".kt": "Kotlin",
        ".swift": "Swift",
        ".php": "PHP",
        ".rb": "Ruby",
    }
    counts: dict[str, int] = {}
    for path in files:
        lang = ext_map.get(path.suffix)
        if lang:
            counts[lang] = counts.get(lang, 0) + 1
    return [name for name, _ in sorted(counts.items(), key=lambda item: item[1], reverse=True)]


def detect_package_managers(names: set[str]) -> list[str]:
    found = []
    checks = {
        "npm": "package-lock.json",
        "pnpm": "pnpm-lock.yaml",
        "yarn": "yarn.lock",
        "Python/uv": "uv.lock",
        "Python/pip": "requirements.txt",
        "Python/Poetry": "poetry.lock",
        "Go modules": "go.mod",
        "Cargo": "Cargo.toml",
    }
    for label, file in checks.items():
        if file in names:
            found.append(label)
    return found


def detect_frameworks(root: Path, files: list[Path]) -> list[str]:
    found: set[str] = set()
    package = root / "package.json"
    if package.exists():
        try:
            data = json.loads(package.read_text())
            deps = {**data.get("dependencies", {}), **data.get("devDependencies", {})}
            for key, label in {"next": "Next.js", "react": "React", "vue": "Vue", "svelte": "Svelte", "vite": "Vite"}.items():
                if key in deps:
                    found.add(label)
        except Exception:
            pass
    names = {p.name for p in files}
    if "pyproject.toml" in names or "requirements.txt" in names:
        text = safe_read(root / "pyproject.toml") + safe_read(root / "requirements.txt")
        for key, label in {"fastapi": "FastAPI", "django": "Django", "flask": "Flask", "pytest": "pytest"}.items():
            if key in text.lower():
                found.add(label)
    if "go.mod" in names:
        found.add("Go")
    if "Cargo.toml" in names:
        found.add("Rust/Cargo")
    return sorted(found)


def detect_commands(root: Path, names: set[str]) -> tuple[list[str], list[str], list[str]]:
    tests: list[str] = []
    builds: list[str] = []
    lints: list[str] = []
    package = root / "package.json"
    if package.exists():
        try:
            scripts = json.loads(package.read_text()).get("scripts", {})
            if "test" in scripts:
                tests.append("npm test")
            if "build" in scripts:
                builds.append("npm run build")
            if "lint" in scripts:
                lints.append("npm run lint")
        except Exception:
            pass
    if "pyproject.toml" in names or "requirements.txt" in names:
        if (root / "tests").exists():
            tests.append("python -m unittest discover -s tests -v")
        else:
            tests.append("python -m pytest")
    if "go.mod" in names:
        tests.append("go test ./...")
        builds.append("go build ./...")
    if "Cargo.toml" in names:
        tests.append("cargo test")
        builds.append("cargo build")
        lints.append("cargo clippy")
    if "Makefile" in names:
        builds.append("make")
    return unique(tests), unique(builds), unique(lints)


def detect_risks(root: Path, files: list[Path], rels: set[str]) -> list[str]:
    risks: set[str] = set()
    lower_rels = {item.lower() for item in rels}
    for label, patterns in RISK_PATTERNS.items():
        for pattern in patterns:
            if any(pattern.lower() in path for path in lower_rels):
                risks.add(label)
    if any(path.name.startswith(".env") for path in files):
        risks.add("local secret files present")
    return sorted(risks)


def top_directories(root: Path, files: list[Path]) -> list[str]:
    counts: dict[str, int] = {}
    for path in files:
        parts = path.relative_to(root).parts
        if len(parts) > 1:
            counts[parts[0]] = counts.get(parts[0], 0) + 1
    return [name for name, _ in sorted(counts.items(), key=lambda item: item[1], reverse=True)[:12]]


def safe_read(path: Path) -> str:
    try:
        return path.read_text(errors="ignore")
    except Exception:
        return ""


def unique(values: list[str]) -> list[str]:
    out = []
    for value in values:
        if value not in out:
            out.append(value)
    return out
